obj-$(CONFIG_MACH_MSM8974_T1_ATT) += board-8974-t1-us.o board-8974-t1-att-gpiomux.o
obj-$(CONFIG_MACH_MSM8974_T1_GLOBAL_COM) += board-8974-t1-global-com.o board-8974-t1-global-com-gpiomux.o

obj-$(CONFIG_LGE_BLUETOOTH) += board-8974-t1-rfkill.o
